# Generated by Django 4.1.3 on 2022-12-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_proddetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proddetails',
            name='Productname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
