# Generated by Django 4.1.3 on 2022-12-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_proddetails_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proddetails',
            old_name='Productname',
            new_name='Name',
        ),
    ]
